# Generated by Django 3.0 on 2019-12-17 10:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('post_title', models.CharField(max_length=255)),
                ('post_description', models.TextField()),
                ('post_description_markdown', models.TextField(blank=True)),
                ('feedback', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('post_author', models.CharField(max_length=255)),
                ('posts_tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
